language: node_js
node_js:
  - 13

services:
  - docker

install:
  - echo "nothing needs to be installed"

before-script:
  - echo "no tests"

script:
  - docker --version
  - docker build -t simple-node .
  - docker tag simple-node tusharkathuria/simple-node:latest

after-success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push tusharkathuria/simple-node