apiVersion: v1
kind: Service
metadata:
  name: simple-node
  labels:
    run: simple-node
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: simple-node
  type: ClusterIP